//Actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT';


//User actions
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const  DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const  DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const  DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const  CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const  CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const  CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const FETCH_TOTAL_PRODUCTS_FAILURE = 'FETCH_TOTAL_PRODUCTS_FAILURE';
export const FETCH_TOTAL_PRODUCTS_REQUEST = 'FETCH_TOTAL_PRODUCTS_REQUEST';
export const FETCH_TOTAL_PRODUCTS_SUCCESS = 'FETCH_TOTAL_PRODUCTS_SUCCESS';

export const FETCH_USER_DISPATCHEDS_REQUEST = 'FETCH_USER_DISPATCHEDS_REQUEST';
export const FETCH_USER_DISPATCHEDS_SUCCESS = 'FETCH_USER_DISPATCHEDS_SUCCESS';
export const FETCH_USER_DISPATCHEDS_FAILURE = 'FETCH_USER_DISPATCHEDS_FAILURE';

export const FETCH_DISPATCHEDS_REQUEST = 'FETCH_DISPATCHEDS_REQUEST';
export const FETCH_DISPATCHEDS_SUCCESS = 'FETCH_DISPATCHEDS_SUCCESS';
export const FETCH_DISPATCHEDS_FAILURE = 'FETCH_DISPATCHEDS_FAILURE';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'; 
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'; 
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'; 

export const FETCH_TOTAL_PRODUCT_REQUEST = 'FETCH_TOTAL_PRODUCT_REQUEST'; 
export const FETCH_TOTAL_PRODUCT_SUCCESS = 'FETCH_TOTAL_PRODUCT_SUCCESS'; 
export const FETCH_TOTAL_PRODUCT_FAILURE = 'FETCH_TOTAL_PRODUCT_FAILURE'; 

export const SUCCESS_ALERT = 'SUCCESS_ALERT';
export const ERROR_ALERT = 'ERROR_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';


//Map actions

export const LOAD_LAYERS_REQUEST = 'LOAD_LAYERS_REQUEST';
export const LOAD_LAYERS_ERROR = 'LOAD_LAYERS_ERROR';
export const LOAD_LAYERS_SUCCESS = 'LOAD_LAYERS_SUCCESS';

export const FETCH_LAYERS_FEATURES_REQUEST = 'FETCH_LAYERS_FEATURES_REQUEST';
export const FETCH_LAYERS_FEATURES_ERROR = 'FETCH_LAYERS_FEATURES_ERROR';
export const FETCH_LAYERS_FEATURES_SUCCESS = 'FETCH_LAYERS_FEATURES_SUCCESS';

export const FILTER_LAYERS = 'FILTER_LAYERS';
export const UPDATE_LAYERS_FEATURES = 'UPDATE_LAYERS_FEATURES';
export const SELECT_LAYER = 'SELECT_LAYER';


export const UPDATE_FEATURES_SUCCESS = 'UPDATE_FEATURES_SUCCESS'
export const UPDATE_FEATURES_ERROR = 'UPDATE_FEATURES_ERROR'
export const UPDATE_FEATURES_REQUEST = 'UPDATE_FEATURES_REQUEST'


//State of pages: loading, loaded, errored;

export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED';
export const LOGIN_PAGE_LOADING = 'LOGIN_PAGE_LOADING';
export const LOGIN_PAGE_ERRORED = 'LOGIN_PAGE_ERRORED';

export const ACTIONS_PAGE_LOADED = 'ACTIONS_PAGE_LOADED';
export const ACTIONS_PAGE_LOADING = 'ACTIONS_PAGE_LOADING';
export const ACTIONS_PAGE_ERRORED = 'ACTIONS_PAGE_ERRORED';

export const REGISTER_PAGE_LOADED = 'REGISTER_PAGE_LOADED';
export const REGISTER_PAGE_LOADING = 'REGISTER_PAGE_LOADING';
export const REGISTER_PAGE_ERRORED = 'REGISTER_PAGE_ERRORED';

export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_LOADING = 'HOME_PAGE_LOADING';
export const HOME_PAGE_ERRORED = 'HOME_PAGE_ERRORED';

export const LIST_PRODUCTS_PAGE_LOADED = 'LIST_PRODUCTS_PAGE_LOADED';
export const LIST_PRODUCTS_PAGE_LOADING = 'LIST_PRODUCTS_PAGE_LOADING';
export const LIST_PRODUCTS_PAGE_ERRORED = 'LIST_PRODUCTS_PAGE_ERRORED';

export const PRODUCT_DETAIL_PAGE_LOADED = 'PRODUCT_DETAIL_PAGE_LOADED';
export const PRODUCT_DETAIL_PAGE_LOADING = 'PRODUCT_DETAIL_PAGE_LOADING';
export const PRODUCT_DETAIL_PAGE_ERRORED = 'PRODUCT_DETAIL_PAGE_ERRORED';

export const DASHBOARD_PAGE_LOADED = 'DASHBOARD_PAGE_LOADED';
export const DASHBOARD_PAGE_LOADING = 'DASHBOARD_PAGE_LOADING';
export const DASHBOARD_PAGE_ERRORED = 'DASHBOARD_PAGE_ERRORED';


